### ISSUE TITLE
doesn't work in vim without a plug manager

### ISSUE THREAD

**Issue by Awan** [ryanoasis/vim-devicons#323] opened 2020-04-23 19:41 UTC
I've put all files in $HOME/.vim/ as per instructions but still isn't working in vim. On same machine, I have created a new user and there in neovim icons are appearing well.

**Comment by Awan** [comment] 2020-04-23 19:44
![image](https://user-images.githubusercontent.com/42554663/80142521-b4b3fc00-85c4-11ea-9701-cf5eafb711a8.png)

**Comment by kazukazuinaina** [comment] 2020-05-14 16:31
Thank you for your report.
As you can see from the screenshots, you can see that the Python icon is correctly rendered in the tabline part that seems to be airline or lightline in the upper right.

Probably lightline.vim?

Judging from this screenshot alone, vim-devicons is working properly. What do you want to expect?

**Comment by Awan** [comment] 2020-05-17 05:30
You didn't understand what I meant. It works with plugin manager. but as in other side by side image posted, it is not working without a plugin manager.

**Comment by kazukazuinaina** [comment] 2020-05-17 05:41
Are you using Vim in the first place? Or do you use Neovim?

How do you put the plugin in the .vim directory?
I'm using Vim, I've placed pluign using the packadd feature under the .vim directory and devicons are working fine.

Please see this reference > https://vim-jp.org/vimdoc-en/repeat.html#:packadd

**Comment by Awan** [comment] 2020-05-17 06:17
![foo](https://user-images.githubusercontent.com/42554663/82137263-e882ea00-982f-11ea-9f08-77098d2b68bb.png)
I'm using vim.

**Comment by Awan** [comment] 2020-05-23 16:40
![image](https://user-images.githubusercontent.com/42554663/82735800-e17f3e80-9d3d-11ea-9e74-4225b275a1dd.png)
![image](https://user-images.githubusercontent.com/42554663/82735813-f78cff00-9d3d-11ea-8cb3-6f66c0408aec.png)

**Comment by kazukazuinaina** [comment] 2020-05-30 14:52
I confirmed that if the plugin's file is placed under  .vim directory in this way, it will work without problems.

I don't think it's a problem with vim-devicons.
So I close this issue.

ps: These screenshots  you provided don't make much sense for issue triage. If you have any problems, please create a new issue according to the issue templete. Thanks!

## dir

```tree
|-- autoload
|   |-- airline
|   |   |-- async.vim
|   |   |-- builder.vim
|   |   |-- debug.vim
|   |   |-- extensions
|   |   |   |-- ale.vim
|   |   |   |-- bookmark.vim
|   |   |   |-- branch.vim
|   |   |   |-- bufferline.vim
|   |   |   |-- capslock.vim
|   |   |   |-- coc.vim
|   |   |   |-- commandt.vim
|   |   |   |-- csv.vim
|   |   |   |-- ctrlp.vim
|   |   |   |-- ctrlspace.vim
|   |   |   |-- cursormode.vim
|   |   |   |-- default.vim
|   |   |   |-- denite.vim
|   |   |   |-- dirvish.vim
|   |   |   |-- eclim.vim
|   |   |   |-- example.vim
|   |   |   |-- fugitiveline.vim
|   |   |   |-- gina.vim
|   |   |   |-- grepper.vim
|   |   |   |-- gutentags.vim
|   |   |   |-- hunks.vim
|   |   |   |-- keymap.vim
|   |   |   |-- languageclient.vim
|   |   |   |-- localsearch.vim
|   |   |   |-- lsp.vim
|   |   |   |-- neomake.vim
|   |   |   |-- netrw.vim
|   |   |   |-- nrrwrgn.vim
|   |   |   |-- obsession.vim
|   |   |   |-- po.vim
|   |   |   |-- poetv.vim
|   |   |   |-- promptline.vim
|   |   |   |-- quickfix.vim
|   |   |   |-- syntastic.vim
|   |   |   |-- tabline
|   |   |   |   |-- autoshow.vim
|   |   |   |   |-- buffers.vim
|   |   |   |   |-- buflist.vim
|   |   |   |   |-- builder.vim
|   |   |   |   |-- ctrlspace.vim
|   |   |   |   |-- formatters
|   |   |   |   |   |-- default.vim
|   |   |   |   |   |-- jsformatter.vim
|   |   |   |   |   |-- short_path.vim
|   |   |   |   |   |-- tabnr.vim
|   |   |   |   |   |-- unique_tail.vim
|   |   |   |   |   |-- unique_tail_improved.vim
|   |   |   |   |   `-- webdevicons.vim
|   |   |   |   |-- tabs.vim
|   |   |   |   |-- tabws.vim
|   |   |   |   `-- xtabline.vim
|   |   |   |-- tabline.vim
|   |   |   |-- tagbar.vim
|   |   |   |-- term.vim
|   |   |   |-- tmuxline.vim
|   |   |   |-- undotree.vim
|   |   |   |-- unicode.vim
|   |   |   |-- unite.vim
|   |   |   |-- vimagit.vim
|   |   |   |-- vimtex.vim
|   |   |   |-- virtualenv.vim
|   |   |   |-- vista.vim
|   |   |   |-- whitespace.vim
|   |   |   |-- windowswap.vim
|   |   |   |-- wordcount
|   |   |   |   `-- formatters
|   |   |   |       `-- default.vim
|   |   |   |-- wordcount.vim
|   |   |   |-- xkblayout.vim
|   |   |   |-- ycm.vim
|   |   |   `-- zoomwintab.vim
|   |   |-- extensions.vim
|   |   |-- highlighter.vim
|   |   |-- init.vim
|   |   |-- msdos.vim
|   |   |-- parts.vim
|   |   |-- section.vim
|   |   |-- themes
|   |   |   `-- dark.vim
|   |   |-- themes.vim
|   |   `-- util.vim
|   |-- airline.vim
|-- plugin
|   |-- airline.vim
|   `-- webdevicons.vim
`-- vimrc
```

## screen shot

<img width="566" alt="スクリーンショット 2020-05-30 23 47 11" src="https://user-images.githubusercontent.com/36619465/83331304-4c95bb80-a2d0-11ea-8dab-551cea152990.png">

**Closed by kazukazuinaina** 2020-05-30 14:52 UTC
Labels: unconfirmed bug
