### ISSUE TITLE
Inconsistent alignment in the presense of nerdtree-git-plugin icons

### ISSUE THREAD

**Issue by nkakouros** [ryanoasis/vim-devicons#223] opened 2018-01-08 01:47 UTC
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)

- [x] What **version** of vim are you using?
  8.0
- [x] What **version** of vim-devicons are you using?
  - 0.9.3
- [x] Are you using vim from the terminal or a GUI vim?
  terminal
- [x] Are you using Mac, Linux or Windows?
  arch linux

#### Optional Info

- [x] Provide **screenshots** where appropriate

When using [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) with devicons and having set `g:WebDevIconsNerdTreeGitPluginForceVAlign` to 1, there is a mismatch in the alignment of the devicons. Here is a screenshot.

![screenshot_20180108_022833](https://user-images.githubusercontent.com/11805218/34656682-bfb719f6-f41d-11e7-8c58-f031e97f5661.jpg)

side note: In the image, there are some other bugs present too (folder names being cutoff at the end when git icons are present, super small devicons, inconsistent right padding between folder icons and file icons).

**Comment by ryanoasis** [comment] 2018-01-11 03:25
@tterranigma thanks for the report :+1:

**Comment by ryanoasis** [comment] 2018-03-09 04:05
@tterranigma I assume you still have this issue?

For me it is looking _okay_ but there is definitely something going on here.

Is there any minimal vimrc you can share? Do you know if you have any other settings other than defaults?

**Comment by ryanoasis** [comment] 2018-03-10 15:34
> super small devicons

You can 'fix' this by using the non-mono version of the font (as long as your terminal supports it). Looks like you are using `Fura Code Regular Nerd Font Complete Mono` ? If so try `Fura Code Regular Nerd Font Complete`

> folder names being cutoff at the end when git icons are present

That's very strange. Not quite sure yet why that'd be. If you remove vim-devicons do those folder names still get cut off? and if you only remove nerdtree-git-plugin do they get cut off? If you remove both? 

> inconsistent right padding between folder icons and file icons

Working on a fix for this

**Comment by tterranigma** [comment] 2018-05-02 09:06
Sorry for not responding earlier. 

After reading [this issue](https://github.com/ryanoasis/nerd-fonts/issues/127), I opened a bug report on KDE's side to discuss it. You can find it [here](https://bugs.kde.org/show_bug.cgi?id=390650). I have no idea if this helps even a little. 

So, I updated everything to their latest versions. I also switched to neovim.

> You can 'fix' this by using the non-mono version of the font (as long as your terminal supports it). Looks like you are using Fura Code Regular Nerd Font Complete Mono ? If so try Fura Code Regular Nerd Font Complete

I tried this but it didn't have any effect. The icons show up with the width of a single letter.

> Not quite sure yet why that'd be. If you remove vim-devicons do those folder names still get cut off? and if you only remove nerdtree-git-plugin do they get cut off? If you remove both?

Here are two screenshots,

with devicons disabled:
![1](https://user-images.githubusercontent.com/11805218/39513923-172ae712-4df6-11e8-9801-90194054ba9f.png)

with both devicons and nerdtree-git disabled:
![1](https://user-images.githubusercontent.com/11805218/39513952-2ae53a1e-4df6-11e8-9300-c8c0b18fc4c3.png)

The same happens if I disable everything in my init.vim except for the two plugins (plus nerdtree of course).

**Comment by kutsan** [comment] 2018-05-02 11:25
@thehappydinoa Have you updated the vim-devicons as well?

**Comment by thehappydinoa** [comment] 2018-05-02 13:27
@kutsan I can look into it, but I'm not sure how helpful I can be

**Comment by kutsan** [comment] 2018-05-02 13:33
@thehappydinoa There was a problem about artifact fix char earlier, and it's [fixed](https://github.com/ryanoasis/vim-devicons/commit/40040ba86e29595cd8c42c1142313793b25d16d9) now. Updating to latest version of this plugin might solve the problem. I am no boss here; if you want, if you are free to look into and try to solve.

**Comment by ryanoasis** [comment] 2018-05-03 00:06
I am working on some more fixes and I'll also merge in @kutsan's PRs. Maybe this week :crossed_fingers:

**Comment by deniskabana** [comment] 2018-06-24 06:50
@ryanoasis I have the same issue and have had it since I starterd using vim-devicons. It looks exactly like the OP's screenshot. All my plugins are up-to-date.

**Comment by kutsan** [comment] 2018-06-24 10:30
@deniskabana Are you sure they are up-to-date? Artifact fix char problem already solved. Can you send me a screenshot and upload your whole `.vim/` folder (or `~/.config/nvim/`) with its plugins to me? I'll try to reproduce the error.

**Comment by deniskabana** [comment] 2018-09-18 15:50
@kutsan I am sorry for the very late reply. I have diagnosed the issue now.

It was only due to the plugin loading ordering - my `vim-devicons` plug was loaded **before** `nerdtree-git-plugin`. I read the wiki when I first set it up, however I installed and removed dozens of plugins over the months I've been using it. Works wonders. Thank you!

**Comment by ryanoasis** [comment] 2019-01-28 04:59
@deniskabana Thanks for the update.

Sorry it has been so long.. so I really was in the middle of merging @kutsan's PRs but then .. lots of things and I haven't been good at all in supporting things lately. Anyway I have renewed desire so hopefully you will see some activity from me (but I'm going to stay away from specific or even rough time lines :disappointed: )

**Comment by ryanoasis** [comment] 2019-02-10 21:38
@tterranigma @thehappydinoa @deniskabana Are any of you still having this issue with the latest version of master branch?

Sorry about the start and stop nature of this issue.

**Comment by tterranigma** [comment] 2019-02-10 22:59
Thanks for looking into this so far. Some issues still persist. Here is an updated screenshot.

![screenshot_20190210_235618](https://user-images.githubusercontent.com/11805218/52540960-ea8a0d80-2d8f-11e9-88af-41d300de62b2.png)

The issues are:

- the opening square at the beginning of the tree
- the off-by-one alignment of the files that have a git icon. This is on the latest Konsole, if it is of any importance.

**Comment by ryanoasis** [comment] 2019-02-11 00:02
Thanks again @tterranigma 

1. Do you have `g:WebDevIconsNerdTreeGitPluginForceVAlign` set?
2. Are you using all default settings (i.e. do you have no DevIcon configurations set in your `vimrc`) ?
3. > * the opening square at the beginning of the tree

    That is odd, did you set something besides the default, you can select if with your cursor and enter `gA` to get the character code, that would be of some help.

4. > * the off-by-one alignment of the files that have a git icon. This is on the latest Konsole, if it is of any importance.

    Should be okay as far as I know

**Comment by tterranigma** [comment] 2019-02-11 15:12
1. Yes
2. I have the following settings for devicons:

```
set guifont=DroidSansMono\ Nerd\ Font\ 19                     
set guifont=Ubuntu\ Mono\ Bold\ Nerd\ Font\ Complete\ Mono\ 12
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '              
let g:webdevicons_conceal_nerdtree_brackets = 1               
let g:WebDevIconsUnicodeDecorateFolderNodes = 1               
let g:DevIconsEnableFoldersOpenClose = 1                      
let g:WebDevIconsNerdTreeGitPluginForceVAlign = 1             
                                                              
if exists('g:loaded_webdevicons')                             
  call webdevicons#refresh()                                  
endif                                                         
```
I commented out everything and I still get the off-by-one padding, plus square brackets around git icons for folders:

![screenshot_20190211_160315](https://user-images.githubusercontent.com/11805218/52571792-96763c00-2e16-11e9-8ab4-2d5e3fcf20c7.png)

3. This is the result of pressing `ga` on the square bracket:
```
<[>  91,  Hex 5b,  Oct 133, Digr <(
```

I also tried the `folder-file-alignment`  branch with no changes to the icon alignment. I also removed all my plugins except devicons, nerdtree and nerdtree git icons and the alignment stayed the same.

**Comment by ryanoasis** [comment] 2019-02-12 03:11
Thanks @tterranigma. I thought at least you'd see some improvement.

I will try to replicate with your settings as best as I can this week if I can...

**Comment by TildeSlashC0re** [comment] 2019-02-12 14:11
I don't seem to run into alignment-issues with **defaults enabled** per-se BUT I do have some artifacts with nerdtree-git-plugin enabled.
(although when enabling the config variables from @tterranigma I can reproduce the results e.g. opening bracket in first list-item of nerdtree)

here's a visual demo
[![pic](https://i.imgur.com/gY14cR9.png)](https://my.mixtape.moe/mclunw.webm)
^ click to get to the webm

**Comment by tterranigma** [comment] 2019-02-13 13:08
My bad... I just went through the doc to see if I have conigured everything properly and, boom, I was loading the git plugin **after** devicons... I changed that and the alignment is perfect. Sorry for keeping you busy with a none issue, really.

The bracket at the beginning still remains.

**Comment by ryanoasis** [comment] 2019-02-14 04:36
Thanks @TildeSlashC0re and @tterranigma 

I think the alignment is much better now and should mostly be consistent with the `folder-file-alignment` branch but I will try to look into the other issues mentioned...

@tterranigma No problem I hadn't really started to try out your settings yet and I needed to work on the alignment issues anyway!

**Comment by ryanoasis** [comment] 2019-06-28 03:53
I am going to consider this closed with #255 merged in. Prefer to open a new issue unless there are still issues related to the original problem per the ticket

**Closed by ryanoasis** 2019-06-28 03:53 UTC

**Comment by nkakouros** [comment] 2019-06-28 09:40
Everything looks great so far! :tada:

**Comment by Azumgi** [comment] 2020-01-04 04:16
If you have misaligned icons, make sure devicons plugin is loaded after nerdtree-git-plugin.
<details>
  <summary>damn it</summary>
  Spent so much time reading the code of 2 extensions to get to the source of the problem. And of course, it's written in readme.
</details>

**Comment by deniskabana** [comment] 2020-01-07 12:58
@ryanoasis We seem to be the rockers of late responses here :) JK, I ditched coding for 6 months and I'm back. All working well on both my mac and linux machines :) Thanks!
