### ISSUE TITLE
vertically stretched icons

### ISSUE THREAD

**Issue by skcc321** [ryanoasis/vim-devicons#78] opened 2015-07-13 16:27 UTC
Don't sure that this is right place where i can ask about this. But...
What shall i do to fix 'stretching' effect?
example: https://goo.gl/KFdkLf
emulator: gnome terminal
font: droid sans mono for powerline plus nerd file types mono 12

**Comment by ryanoasis** [comment] 2015-07-14 00:03
@skcc321 this is an okay place to ask. font related should probably go on https://github.com/ryanoasis/nerd-fonts but since the primary use is this vim plugin this is where most issues get posted :smile: 

I think the issue is with the 'mono' variation of the fonts. the patcher as it currently stands is definitely not perfect in how the glyphs come out unfortunately :cry: but I am still working on it :smile: 

Yeah looks like with gnome terminal you *have* to give a 'true mono' font and they don't look as good right now.

For instance here is mine:
![selection_13_07_15_20 01 51_182x382_001](https://cloud.githubusercontent.com/assets/8083459/8663524/074a45dc-299a-11e5-9291-5109bd66dc66.png)

So thanks for the report! This is something that should be improved, some look a lot worse than the others, in your case I take it you are mostly dev with ruby and those look particularly bad :laughing:

**Comment by skcc321** [comment] 2015-07-14 08:10
Yeah, ruby icon is awful in this case. :)
Thanks, for a rapid response.

**Comment by ryanoasis** [comment] 2015-07-18 14:21
@skcc321 I may close this issue and open one in the [font-patcher](https://github.com/ryanoasis/nerd-fonts) but I have not decided yet because this project has more visibility and it is easier to remember open issues here :smile: . Maybe best to leave this open _and_ create one in nerd-fonts

**Comment by rscircus** [comment] 2015-10-07 20:16
+1. Using gnome-terminal on Linux Mint 17.2 - pretty vanilla... 😕

**Comment by ryanoasis** [comment] 2015-10-07 21:06
@rscircus Yes give that a try. Let me know if it does or does not. :smile: 

Hopefully it should work for you (to use the double width glyphs). Fixing the single width glyphs will not be an easy or quick coming solution

**Comment by cj** [comment] 2015-10-08 04:33
@ryanoasis The font I'm using is `Pragmata Pro` I've tried single and double width.  I've also tried mono and not mono version of the fonts in both styles.  Still the same issue :/

**Comment by rscircus** [comment] 2015-10-08 05:59
@ryanoasis, OK, it worked out. 👍💫 However, I was a bit confused, as gnome-terminal shows "DejaVu Sans Mono for Powerline" for the patched font using double-width glyphs and happily ignored all the other patched icon-names in the TTF filename.

**Comment by s0r00t** [comment] 2016-05-20 17:07
Using patched complete Inconsolata Mono, still having stretched icons in gVim.

**Comment by ryanoasis** [comment] 2017-05-02 22:26
Hey all (@skcc321, @rscircus, @cj, et al).

Sorry it's been a while since this was updated but this issue has been fixed  in [Nerd Fonts since v1.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v1.0.0)

### Example
**Here is an example with Droid (notice it is mono but no longer stretched):**

![preview of mono stretching fixed](https://cloud.githubusercontent.com/assets/8083459/25641815/3c142e50-2f64-11e7-8c93-3c46380ff937.png)

Also.. default ruby glyph has since been updated to a better option:
![selection_009](https://cloud.githubusercontent.com/assets/8083459/25641956/d1079ff6-2f64-11e7-8f90-b2e7df6ccff3.png)


Closing this for now... however, feel free to ping on here (especially if you are still having the issue).

**Closed by ryanoasis** 2017-05-02 22:26 UTC
Labels: font patcher, ⚠ confirmed bug, ✨ enhancement
