### ISSUE TITLE
NERDTree conceal brackets in file names

### ISSUE THREAD

**Issue by flippidippi** [ryanoasis/vim-devicons#278] opened 2019-07-31 20:07 UTC
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin?
- [x] What **version** of vim are you using?
  - NVIM v0.3.7
- [x] What **version** of vim-devicons are you using?
  - 0.11.0
- [x] Are you using vim from the terminal or a GUI vim?
    - iTerm2 3.2.7
- [x] Are you using Mac, Linux or Windows?
    - macOS 10.14.6

#### Optional Info

When using NERDTree, if a filename has brackets then they are not shown in NERDTree.
So for a file named `[id].js`, NERDTree only displays `id.js`.

If I turn off conceal NERTree brackets like `let g:webdevicons_conceal_nerdtree_brackets=0` then it will show the brackets in the filename but also show brackets around the icons which is unwanted.

Without setting `let g:webdevicons_conceal_nerdtree_brackets=0`:
<img width="278" alt="Screen Shot 2019-07-31 at 3 05 52 PM" src="https://user-images.githubusercontent.com/1396568/62244335-d620e800-b3a4-11e9-874c-1be8f9593993.png">

With settting `let g:webdevicons_conceal_nerdtree_brackets=0`
<img width="272" alt="Screen Shot 2019-07-31 at 3 06 21 PM" src="https://user-images.githubusercontent.com/1396568/62244371-eafd7b80-b3a4-11e9-8e85-b5ec5c8651f9.png">

**Comment by ryanoasis** [comment] 2019-10-18 02:59
Hah interesting right... Yes, this should be fixed.

**Comment by kazukazuinaina** [comment] 2019-10-25 08:47
I also reproduced the problem.

**Comment by Goku-San** [comment] 2020-02-04 18:50
Hello @ryanoasis , I have similar problem
I can't get rid of the brackets in Gvim, I have tired your solutions from earlier posts about this problem, but none of them work.

I am on **linux** and **terminal vim** works just fine with the settings you provide in the ``` wiki#usage ```.
So is there a way to disable them completle ??

**Comment by ryanoasis** [comment] 2020-02-19 06:14
hey @Goku-San I take it you looked at https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#square-brackets-around-icons ?

Also perhaps it is possible your gvim is built with different options than your vim ?
`:echo has('conceal')`

**Comment by Goku-San** [comment] 2020-02-19 11:07
Hi @ryanoasis yes I've looked at FAQ about the square brackets. According to that all should be ok
```:echo has('conceal')``` on Gvim is ```1``` so that's good.
![gVimBrackets](https://user-images.githubusercontent.com/22682262/74824073-0495ee80-5308-11ea-8ae8-5e3c9f92fb5c.png)

Also, now I have noticed that the icons are not showing properly
my **Gvim version is 8.2, guifont = FiraCode Nerd Font Medium 12**

**Comment by Goku-San** [comment] 2020-02-19 18:01
Hi @ryanoasis, I fixed the problem with the **brackets**. It was my fault all along, **sorry** for wasting your time, I had **.gvimrc** and **.vimrc** so they were in conflict, now I deleted *.gvimrc* and created a regular ```gvim.vim``` file with only things that concern Gvim, and I sourced it through ```.vimrc``` and all is good, except the font. I don't know how to fix that or if it needs fixing at all.

When I ```set guifont=FiraCode\ Nerd\ Font\ Medium\ 12``` icons are not showing properly in Gvim, but when   ```set guifont=Fira\ Code\ Medium\ 12``` they are oki. 

Again, sorry for wasting your time.

**Comment by ryanoasis** [comment] 2020-02-23 06:55
@Goku-San no worries. glad you got it sorted out.

**Comment by apoutchika** [comment] 2020-04-20 17:54
Hi,

I have the same problème. 

This line replace all brackets in Nerdtree ?
https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L357

Has you solution for change only first bracket on line ?

Thank you

**Comment by ryanoasis** [comment] 2020-04-20 23:05
@apoutchika Yes that's correct as long as the `conceal` feature is there in your build of vim.

> Has you solution for change only first bracket on line ?

That is still a known issue I believe for some. Can you post a screenshot?

**Comment by apoutchika** [comment] 2020-04-21 05:31
Thank you @ryanoasis for you'r fast response !

This is a screenshot without configuration :

![image](https://user-images.githubusercontent.com/3884759/79828337-d6cd3480-83a0-11ea-88d4-2850385fc35e.png)

But, if I add `let g:webdevicons_conceal_nerdtree_brackets = 0` in my vimrc, all brackets is OK

![image](https://user-images.githubusercontent.com/3884759/79828428-f5333000-83a0-11ea-9d39-1998b833f7fa.png)

I would like to have this result: 
```
.. (up a dir)
  /tmp/devicon/
  ▾  [test2]/
       [test3].js
```
( is icon)

It's Next js who use bracket in filename for dynamic routes : https://nextjs.org/docs/basic-features/pages#pages-with-dynamic-routes

Thank you for you'r help

**Closed** 2020-04-26 15:22 UTC

**Comment by FedericoBruzzone** [comment] 2023-04-23 15:05
It works for me

```
let g:rainbow_active = 0

autocmd FileType * let g:rainbow_active=1
```
