### ISSUE TITLE
CtrlPBuffer shows [No Name] instead of buffer file name

### ISSUE THREAD

**Issue by extrante** [ryanoasis/vim-devicons#183] opened 2016-10-27 21:45 UTC
#### Required Info
- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] What **version** of vim are you using?

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 24 2016 17:33:26)
Parches incluidos: 1-46
Compilado por Arch Linux
- [x] What **version** of vim-devicons are you using?

0.8.5
- [x] Are you using vim from the terminal or a GUI vim?

gvim
- [x] Are you using Mac, Linux or Windows?

Linux

Screenshot:

![ctrlp](https://cloud.githubusercontent.com/assets/17460166/19786277/6cb0c230-9c9d-11e6-8592-3c1769af17c6.png)

With let g:webdevicons_enable_ctrlp = 0 filenames are shown correctly.

I noticed this happens from ctrlpvim/ctrlp.vim@28612d023ccf889c10155cf9d17e44b3a2e7c060 Previous commit seems to be working ok with let g:webdevicons_enable_ctrlp = 1

Current version ctrlpvim/ctrlp.vim@c6d1fc5e58d689bfb104ff336aeb89d9ef1b48e2 is also affected, of course.

**Comment by smesko85** [comment] 2016-10-31 10:43
@extrante I just had same issue. I fixed it by loading vim-devicons before ctrlp plugin.
Hope this works for you too.

**Comment by lerrua** [comment] 2016-11-04 16:41
@smesko85 your solution works fine for me.

**Comment by extrante** [comment] 2016-11-06 11:38
It works for me too, but https://github.com/ryanoasis/vim-devicons#usage says you have to load CtrlP before vim-devicons loads. Docs should be updated if there's no proper fix to this problem.

**Comment by darrinholst** [comment] 2016-11-11 15:25
For me loading devicons before ctrlp has the same effect as configuring ctrlp support off. You get buffer names back, but you don't get any of the icons.

**Comment by HerringtonDarkholme** [comment] 2016-11-18 03:36
The easiest fix is change the line g:ctrlp_formatline_func to 

`let g:ctrlp_formatline_func = 's:formatline(s:curtype() == "buf" ? v:val : WebDevIconsGetFileTypeSymbol(v:val) . " " . v:val) '
`

**Comment by PezCoder** [comment] 2016-11-25 17:32
@HerringtonDarkholme The mentioned line fixed the issue but the icons devicons icons are not coming in buffer search. Can I get it somehow ?

**Comment by ryanoasis** [comment] 2016-11-25 17:44
@PezCoder I think this would require a PR, see: https://github.com/ryanoasis/vim-devicons/pull/185#issuecomment-261690023

**Comment by ryanoasis** [comment] 2016-12-10 14:18
Closing this as the root cause is now fixed. As @PezCoder mentioned the icons will no longer show up but that will require another PR to CtrlP :blush:

**Closed by ryanoasis** 2016-12-10 14:18 UTC
Labels: ⚠ confirmed bug
