### ISSUE TITLE
After Plug Update, all icons became the same color in NerdTree

### ISSUE THREAD

**Issue by vando026** [ryanoasis/vim-devicons#330] opened 2020-05-11 08:24 UTC
Between commits 58e57b6 and 0b6a7bd, my custom icon colors in NerdTree changed to all the same color. 

Commit 58e57b6

![Commit_58e57b6](https://user-images.githubusercontent.com/36604253/81539679-e375f480-9370-11ea-8400-ecee2afdc9cd.PNG)

Commit 0b6a7bd

![Commit_0b6a7bd](https://user-images.githubusercontent.com/36604253/81539701-ed97f300-9370-11ea-8df6-077b2c816a8a.PNG)

All else stays the same and this behaviour is obtained by toggling the commits in my vimrc. 

![Toggle](https://user-images.githubusercontent.com/36604253/81539589-c0e3db80-9370-11ea-876d-83e1057c474d.PNG)

#### Required Info

- [ x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful 
- [x ] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting) 
- [ x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) X
- [tiagofumo after devcons ] `VimDevIcons` is the last loaded vim plugin?
- [ 8.2] What **version** of vim are you using?
  - hint: `vim --version` 
- [0.11.0 ] What **version** of vim-devicons are you using?
  - hint: `:echo webdevicons#version()` 
- [GUI ] Are you using vim from the terminal or a GUI vim?
- [ Windows] Are you using Mac, Linux or Windows? Windows

#### Optional Info

- [ ] Provide **screenshots** where appropriate

**Comment by taq** [comment] 2020-05-13 21:09
I'm also facing the same situation. I was searching for "color" here and found this issue.

**Comment by Menn1s** [comment] 2020-05-14 06:02
Hi, I've been having issues getting any highlighting to work on only the glyphs. I could only get it to apply to the entire filename and the glyph (but when highlighting does work, it would add brackets). 
Could I see the section of your vimrc that adds color? I could not get any of the other instructions to work properly

**Comment by tiagofneto** [comment] 2020-05-14 14:59
I also have the same problem, currently using commit 58e57b6.

**Comment by kazukazuinaina** [comment] 2020-05-14 16:52
Thanks for report.
How about this patch?
Please try this.

```diff
diff --git a/plugin/webdevicons.vim b/plugin/webdevicons.vim
index f4d9263..f3274b1 100644
--- a/plugin/webdevicons.vim
+++ b/plugin/webdevicons.vim
@@ -364,8 +364,8 @@ function! s:setSyntax()
   if g:webdevicons_enable_nerdtree == 1 && g:webdevicons_conceal_nerdtree_brackets == 1
     augroup webdevicons_conceal_nerdtree_brackets
       au!
-      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=NERDTreeFlags
-      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=NERDTreeFlags
+      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=NERDTreeFile,NERDTreeExecFile,NERDTreeDir,NERDTreeFlags
+      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=NERDTreeFile,NERDTreeExecFile,NERDTreeDir,NERDTreeFlags
       autocmd FileType nerdtree setlocal conceallevel=3
       autocmd FileType nerdtree setlocal concealcursor=nvic
     augroup END
```

**Comment by taq** [comment] 2020-05-14 19:25
Em qui., 14 de mai. de 2020 às 13:52, IK <notifications@github.com>
escreveu:

> Thanks for report.
> How about this patch?
>
Seems the patch worked!

>

**Comment by taq** [comment] 2020-05-14 19:26
Uh, where is the @kazukazuinaina content with the patch I just got on email?

**Comment by kazukazuinaina** [comment] 2020-05-14 19:32
@taq 

In that patch, the following bug was reproduced, so I delete it.
Sorry for the confusion.

> https://github.com/ryanoasis/vim-devicons/issues/278

**Comment by taq** [comment] 2020-05-14 19:36
Oh, ok, but for this issue here, it solved the problem. But, a file called [id].js ? I'd rather fix my colors than think in finding file names with brackets. :-)

**Comment by vando026** [comment] 2020-05-16 19:20
Hi Just following up on this, the person that made the commit at 0b6a7bd  is below

0b6a7bd - Phil Runninger, 4 weeks ago : Ensure only the brackets around the flags are concealed.

Shouldnt we try to contact him?

**Comment by her** [comment] 2020-05-22 01:32
@vando026 are you using the `tiagofumo/vim-nerdtree-syntax-highlight` plugin?

**Comment by vando026** [comment] 2020-05-22 13:08
Yes I am, and I have it loaded last straight after ryanoasis/vim-devicons.

**Comment by Ninlives** [comment] 2020-05-26 02:35
> Oh, ok, but for this issue here, it solved the problem. But, a file called [id].js ? I'd rather fix my colors than think in finding file names with brackets. :-)

Do you have a copy of that patch? Thanks :)

**Comment by polyzen** [comment] 2020-05-26 02:51
@Ninlives, see #332.

**Comment by her** [comment] 2020-05-26 19:28
Hey y'all, we closed this PR as it would introduce regressions with conceal of files where the names have square brackets in them, e.g. `[id].js` 

For an interim highlighting solution for DevIcons see https://github.com/her/synicons.vim

**Comment by her** [comment] 2020-05-27 03:33
this is now fixed in https://github.com/tiagofumo/vim-nerdtree-syntax-highlight/commit/bb0a941f01a619a1dc2880795b39bbbd4ff9f247  tiagofumo/vim-nerdtree-syntax-highlight/commit/

**Comment by kazukazuinaina** [comment] 2020-05-27 03:35
@her 

Thanks!

**Closed** 2020-05-27 03:34 UTC
Labels: help wanted, possible bug

**Comment by taq** [comment] 2020-05-27 12:18
@her I just installed your plugin (removing the patched @tiagofumo one) but now my NerdTree is back to no colors again. :-(

**Comment by taq** [comment] 2020-05-27 12:28
Weird stuff. I was using the patched devicons, just removed it and back to @tiagofumo plugin, removing everything and installing again with fresh copies seems to solved my problem.

**Comment by vando026** [comment] 2020-05-27 16:17
@her thanks this worked for me too.

**Comment by her** [comment] 2020-05-27 19:02
That’s great y’all! Glad it’s back to normal 👍

**Comment by SubhamBurnwal** [comment] 2021-01-18 15:04
Okay,,, so I tried to follow this discussion and its confused me even more. All my icons are having the same color as was the case with all of you. I have the latest versions of everything installed since it was just yesterday I called PlugUpdate.
Do the following settings in .vimrc affect something?
```
Plug 'vim-airline/vim-airline'                                                                                     
Plug 'vim-airline/vim-airline-themes'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts = 1
Plug 'ryanoasis/vim-devicons'
```

**Comment by BenHerbst** [comment] 2021-12-31 03:46
I also have the same issue

**Comment by ensia96** [comment] 2022-10-15 16:51
I have same problem after updating nvim to 0.8.0 (I also updated nvim plugins too)

**Comment by sforli** [comment] 2023-03-07 23:07
The problem is still here, I've tried calling the plugin before and after tiagofumo's syntax highlight, and the commit at the beginning of this issue.
Did I miss something?

**Comment by xiantang** [comment] 2023-04-09 11:10
I installed "her/synicons.vim" then resolved

NVIM v0.8.3
